services:
  server:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /workspace
    volumes:
      - ./:/workspace:cached
    networks:
      - devnet
    ports:
      - "5020:5020"
    command: tail -f /dev/null

networks:
  devnet:
    external: true
